### ISSUE TITLE
Not able to scrape cs:ai papers

### ISSUE THREAD

**Issue by pritishmishra703** [Mahdisadjadi/arxivscraper#21]
Not able to scrape from cs:ai

```
import arxivscraper.arxivscraper as ax
import pandas as pd

scraper = ax.Scraper(category='cs:ai', date_from='2023-06-1',date_until='2023-06-6')
output = scraper.scrape()

cols = ('id', 'title', 'categories', 'abstract', 'doi', 'created', 'updated', 'authors')
df = pd.DataFrame(output, columns=cols)
df.to_csv('data/research_papers/data.csv', index=False)
```

Returns:

```
fetching up to  1000 records...
Traceback (most recent call last):
  File "c:\pritish\FineTuneLLaMA2\test.py", line 8, in <module>
    df = pd.DataFrame(output, columns=cols)
  File "C:\Users\priti\anaconda3\lib\site-packages\pandas\core\frame.py", line 817, in __init__
    raise ValueError("DataFrame constructor not properly called!")
ValueError: DataFrame constructor not properly called!
```

I checked the variable `output` is just int `1`. I expected a list.

**Comment by Mahdisadjadi** [comment]
@pritishmishra703 : Thank you for raising this issue. Could you please retry using this?


```
import arxivscraper.arxivscraper as ax
import pandas as pd

scraper = ax.Scraper(
    category="cs",
    date_from="2023-06-01",
    date_until="2023-06-02",
    t=10,
    filters={"categories": ["cs.ai"]},
)
output = scraper.scrape()
```

I think main issue was date format : `'2023-06-6'` to `'2023-06-06'`. But I also moved `ai` to `filter`.

**Comment by pritishmishra703** [comment]
Worked! Thanks a lot.
